######################################################################
# Automatically generated by qmake (2.01a) Fri May 30 12:06:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FacetagsDetection.h FacetagsUI.h
FORMS += mainwindow.ui
SOURCES += FacetagsDetection.cpp FacetagsMain.cpp FacetagsUI.cpp
