######################################################################
# Automatically generated by qmake (2.01a) Di. Jul 22 22:31:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../readWriteObjectFile.h ../FaceObject.h
SOURCES += drawBBs.cpp ../readWriteObjectFile.cpp ../FaceObject.cpp

unix: CONFIG += link_pkgconfig
unix: PKGCONFIG += opencv
